spring:
  datasource:
    url: jdbc:mysql://39.100.126.5:3306/ocr??useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=true
    username: paper
    password: qaz2580...
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #初始化连接
    initialSize: 5
    #最小空闲连接
    minIdle: 5
    #最大连接数量
    maxActive: 20
    #<!-- 超时等待时间以毫秒为单位 6000毫秒/1000等于60秒 --
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 500Mb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    ip-address: true
management.security.enabled: false
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

path:
  native:
    out-path: C:\data\
    temp-path: C:\data\a.png #本地测试
#    out-path: /usr/project/server/img/
#    temp-path: /usr/project/server/img/a.png #服务器地址